/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BingoBoard: typeof import('./../components/bingo-board.vue')['default']
    BingoCell: typeof import('./../components/bingo-cell.vue')['default']
    BingoGame: typeof import('./../components/bingo-game.vue')['default']
    BingoHelp: typeof import('./../components/bingo-help.vue')['default']
    BingoTimer: typeof import('./../components/bingo-timer.vue')['default']
    DefaultLayout: typeof import('./../layouts/default-layout.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPopover: typeof import('naive-ui')['NPopover']
    NProgress: typeof import('naive-ui')['NProgress']
    QuizAnswerButton: typeof import('./../components/quiz-answer-button.vue')['default']
    QuizAnswerList: typeof import('./../components/quiz-answer-list.vue')['default']
    QuizCountdown: typeof import('./../components/quiz-countdown.vue')['default']
    QuizNameInput: typeof import('./../components/quiz-name-input.vue')['default']
    QuizQuestion: typeof import('./../components/quiz-question.vue')['default']
    QuizQuestionText: typeof import('./../components/quiz-question-text.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheNav: typeof import('./../components/the-nav.vue')['default']
  }
}
