name: Run GitHub Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: cps
  DOCKER_REGISTRY_URL: ghcr.io

jobs:
  check-types:
    environment: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npx pnpm install

      - name: Check Types
        run: |
          npx pnpm run typecheck

  lint:
    environment: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npx pnpm install

      - name: Lint
        run: |
          npx pnpm run lint

  run-tests:
    environment: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npx pnpm install

      - name: Run Tests
        run: |
          npx pnpm run test

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    environment: build
    env:
      VITE_BACKEND_URL: ${{ vars.VITE_BACKEND_URL }}
      VITE_WEBSOCKET_URL: ${{ vars.VITE_WEBSOCKET_URL }}
      VITE_WEBSOCKET_PATH: ${{ vars.VITE_WEBSOCKET_PATH }}
      VITE_GOOGLE_AUTH_CLIENT_ID: ${{ secrets.VITE_GOOGLE_AUTH_CLIENT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . \
          --file Dockerfile \
          --tag $DOCKER_REGISTRY_URL/alexvoedi/$DOCKER_IMAGE_NAME:latest \
          --build-arg VITE_BACKEND_URL=$VITE_BACKEND_URL \
          --build-arg VITE_WEBSOCKET_URL=$VITE_WEBSOCKET_URL \
          --build-arg VITE_WEBSOCKET_PATH=$VITE_WEBSOCKET_PATH \
          --build-arg VITE_GOOGLE_AUTH_CLIENT_ID=$VITE_GOOGLE_AUTH_CLIENT_ID

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ${{env.DOCKER_REGISTRY_URL}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Push the latest tag
        run: docker push $DOCKER_REGISTRY_URL/alexvoedi/$DOCKER_IMAGE_NAME:latest

      - name: Remove the Docker image with latest tag
        run: docker rmi $DOCKER_REGISTRY_URL/alexvoedi/$DOCKER_IMAGE_NAME:latest
