name: Run GitHub Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  VITE_BACKEND_URL: ${{ vars.VITE_BACKEND_URL }}
  VITE_WEBSOCKET_URL: ${{ vars.VITE_WEBSOCKET_URL }}
  VITE_GOOGLE_AUTH_CLIENT_ID: ${{ secrets.VITE_GOOGLE_AUTH_CLIENT_ID }}

jobs:
  check-types:
    environment: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npx pnpm install

      - name: Check Types
        run: |
          npx pnpm run typecheck

  lint:
    environment: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npx pnpm install

      - name: Lint
        run: |
          npx pnpm run lint

  run-tests:
    environment: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npx pnpm install

      - name: Run Tests
        run: |
          npx pnpm run test

  build:
    environment: build
    runs-on: ubuntu-latest
    needs:
      - lint
      - run-tests
      - check-types
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npx pnpm install

      - name: Build
        run: |
          npx pnpm run build
          cp dist/index.html dist/404.html
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist

  deploy:
    environment: build
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: dist
          folder: dist
