name: Run GitHub Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Dependencies
        run: |
          npx taze minor
          npx pnpm update

      - name: Commit Changes
        run: |
          git config --local user.email "alexander.voedisch@gmail.com"
          git config --local user.name "Alexander Vödisch"
          git diff --quiet || git commit -am "chore: update dependencies"

  check-types:
    runs-on: ubuntu-latest
    needs: update-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npx pnpm install

      - name: Check Types
        run: |
          npx pnpm run typecheck

  lint:
    runs-on: ubuntu-latest
    needs: update-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npx pnpm install

      - name: Lint
        run: |
          npx pnpm run lint

  run-tests:
    runs-on: ubuntu-latest
    needs: update-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npx pnpm install

      - name: Run Tests
        run: |
          npx pnpm run test

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - run-tests
      - check-types
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npx pnpm install

      - name: Build
        run: |
          npx pnpm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: dist
          folder: dist
